steps:
  # Fetch previous branches for `git diff` to work in script
  # - name: gcr.io/cloud-builders/git
  #   args: ['fetch', 'origin', '${_BASE_BRANCH}:refs/remotes/origin/${_BASE_BRANCH}']
  # # Set up gcloud
  # - name: gcr.io/cloud-builders/gcloud
  #   args: ['config', 'list']
  # Show the gcloud info
  - name: ${_PYTHON_IMAGE}
    entrypoint: /bin/sh
    args:
    - -c
    - 'gcloud config list'
  # Show the Python version
  - name: ${_PYTHON_IMAGE}
    entrypoint: /bin/sh
    args:
    - -c
    - 'python3 --version'
  # Install Python dependencies and run testing script
  - name: ${_PYTHON_IMAGE}
    entrypoint: /bin/sh
    args:
    - -c
    - 'python3 -m pip install -U -r .cloud-build/requirements.txt && python3 -m pip freeze && .cloud-build/run_notebooks_only_diff.sh'
    env:
    - 'PROJECT_ID=${PROJECT_ID}'
    - 'REGION=${_DEPLOY_REGION}'
    - 'BUCKET_NAME=${_ROOT_BUCKET_NAME}'
    - 'BASE_BRANCH=${_BASE_BRANCH}'
    - 'AUTORUN=1'
    - 'ARTIFACTS_FOLDER=${BUILD_ID}'
  # Manually copy artifacts to GCS
  - name: gcr.io/cloud-builders/gsutil
    entrypoint: /bin/sh
    args: 
    - -c
    - 'if [ $(ls -pR "/workspace/${BUILD_ID}"  | grep -v / | grep -v ^$ | wc -l) -ne 0 ]; then gsutil rsync -r "/workspace/${BUILD_ID}" "gs://${_ROOT_BUCKET_NAME}/test-artifacts/PR_${_PR_NUMBER}/BUILD_${BUILD_ID}/"; else echo "No artifacts to copy."; fi'
  # Fail if there is anything in the error folder
  - name: ${_PYTHON_IMAGE}
    entrypoint: /bin/sh
    args: 
    - -c
    - 'echo "Download executed notebooks with this command: \"mkdir -p artifacts && gsutil rsync -r gs://${_ROOT_BUCKET_NAME}/test-artifacts/PR_${_PR_NUMBER}/BUILD_${BUILD_ID} artifacts/\"" && if [ "$(ls -A /workspace/${BUILD_ID}/error | wc -l)" -ne 0 ]; then exit 1; else exit 0; fi'
# artifacts:
#   objects:
#     location: 'gs://${_ROOT_BUCKET_NAME}/test-artifacts/PR_${_PR_NUMBER}/BUILD_${BUILD_ID}/'
#     paths: ['/workspace/${BUILD_ID}/*']       
timeout: 10800s
